steps: 
  - name: gcr.io/$PROJECT_ID/hugo
    args: [
      "-s","hugo",
      "-d","../public"
      ]

 # create a docker container that can run on cloud run
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "tools/preview_container/Dockerfile", "-t", "gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA"]

  # deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:305.0.0
    entrypoint: gcloud
    args: [
    'run', 'deploy', 'stanke-dev', 
    '--image', 'gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA', 
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--quiet'
    ]
