--- 
secrets: 
  - 
    kmsKeyName: projects/stanke-dev/locations/global/keyRings/stanke-dev/cryptoKeys/firebase
    secretEnv: 
      FIREBASE_TOKEN: "CiQAHwp0p2sJGymNgyouoYpBNhf8aRae7RMhD0iPAkzWFQWu2x4SVgBc5WTz0W2fpKaftNI53i7V
m8t4+mB4UCJR68+p0s7DYBE1YAq3VDKz2oPGFGLNR3Mkfakxuxryms47Eny4WDUvmA1HymmOkj/5
VdnWxuLf6OW6mxiQ"
steps: 
  - 
    args: 
      - "-c"
      - "firebase deploy --project=$PROJECT_ID --only=hosting --token=$$FIREBASE_TOKEN\n"
    entrypoint: bash
    name: gcr.io/$PROJECT_ID/firebase
    secretEnv: 
      - FIREBASE_TOKEN