steps: 
  - name: gcr.io/$PROJECT_ID/hugo
    args: [
      "-s","hugo",
      "-d","../public"
      ]

 # create a docker container that can run on cloud run
 # TODO: skip this step if container already exists
 # (which it *should*, because it should have been built as part of CI for PRs,
 # but if an admin skips PR, then it will need to be built fresh)
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "tools/preview_container/Dockerfile", "-t", "gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA"]

  # deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud@sha256:3971d22114ad25262ee04e9161020c5145cc8eb65f710f3cc22d0f4b47a78984
    entrypoint: gcloud
    args: [
    'run', 'deploy', 'stanke-dev-new', 
    '--image', 'gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA', 
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--quiet'
    ]