steps:
  - name: gcr.io/$PROJECT_ID/hugo
    id: 'hugo'
    args: [
      "-s","hugo",
      "-d","../public"
      ]
    waitFor: ['-']

  - name: ubuntu
    id: 'sed'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - 'tools/nginx_container/create_redirects.sh'
    waitFor: ['-']

  # create a docker container that can run on cloud run
  - name: gcr.io/cloud-builders/docker
    id: 'build'
    args: [
      "build", "-f", "tools/nginx_container/Dockerfile", 
      "-t", "gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA", "."
      ]
    waitFor: ['hugo', 'sed']
  
  - name: gcr.io/cloud-builders/docker
    id: 'push'
    args: ["push","gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA"]
    waitFor: ['build']


  # deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:309.0.0-slim
    id: 'deploy'
    entrypoint: gcloud
    args: [
      'alpha', 'run', 'deploy', 'stanke-dev',
      '--image=gcr.io/stanke-dev/stanke-dev:commit$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--tag=commit$SHORT_SHA',
      '--no-traffic',
      '--quiet'
    ]
    waitFor: ['push']

  # add preview URL as a status check
  - name: 'gcr.io/${PROJECT_ID}/pr-status-poster'
    id: 'status'
    args: [
      '--project-id', '${PROJECT_ID}', 
      '--repo-name', 'davidstanke/${REPO_NAME}',
      '--commit-sha', '${COMMIT_SHA}',
      '--target-url', 'https://commit$SHORT_SHA---stanke-dev-t63odkzjiq-uc.a.run.app'
    ]
    waitFor: ['deploy']