steps:
  - name: gcr.io/$PROJECT_ID/hugo
    args: [
      "-s","hugo",
      "-d","../public"
      ]

  # create a docker container that can run on cloud run
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "tools/preview_container/Dockerfile", "-t", "gcr.io/$PROJECT_ID/site-preview:$SHORT_SHA", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/site-preview:$SHORT_SHA"]

  # deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: 
      - "-c"
      - |
        gcloud beta run deploy stanke-dev-preview-$SHORT_SHA --image=gcr.io/stanke-dev/site-preview:$SHORT_SHA --platform=managed --region=us-central1 --allow-unauthenticated
        echo $(gcloud beta run services describe stanke-dev-preview-$SHORT_SHA --platform=managed --region=us-central1 --format="value(status.address.url)") > /workspace/url.txt

  # add preview URL as a comment on Pull Request
  - name: gcr.io/$PROJECT_ID/pr-commenter
    args: [
      "$_PR_NUMBER",
      "davidstanke/stanke.dev",
      "this is my comment!",
      "$$GITHUB_TOKEN" 
    ]
    secretEnv: 
      - GITHUB_TOKEN  

  # # add preview URL as a comment on Pull Request
  # - name: gcr.io/cloud-builders/curl
  #   entrypoint: bash
  #   args: 
  #     - "-c"
  #     - |
  #       echo "{\"body\": \"Preview this revision: $(cat /workspace/url.txt)\"}" > /workspace/api_payload.txt && \
  #       curl -s -H "Authorization: token $$GITHUB_TOKEN" -X POST -d @/workspace/api_payload.txt "https://api.github.com/repos/davidstanke/stanke.dev/issues/$_PR_NUMBER/comments"

  #   secretEnv: 
  #     - GITHUB_TOKEN

secrets:
  - kmsKeyName: projects/stanke-dev/locations/global/keyRings/stanke-dev/cryptoKeys/github-access-token
    secretEnv: 
      GITHUB_TOKEN: "\
      CiQApWZD3glqQqWrQokId3TuRrWfBMPTtu/B1ccsr+VKlAvFJGQSUQBLWP5TLHS\
      hG81/eGy20mkRBMYv/HBBlrAl+hCInE4UMXDerAFDBAUlV4gvt/32Idi1spAk/T8\
      PW8nsu8q946j7+9sP5mJo7ZBTauLmKYLLeg=="
