steps:
  - name: gcr.io/$PROJECT_ID/hugo
    args: [
      "-s","hugo",
      "-d","../public"
      ]

  # create a docker container that can run on cloud run
  - name: gcr.io/cloud-builders/docker
    args: [
      "build", "-f", "tools/nginx_container/Dockerfile", 
      "-t", "gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA", "."
      ]
  - name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/stanke-dev:commit$SHORT_SHA"]


  # deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:309.0.0-slim
    entrypoint: gcloud
    args: [
      'alpha', 'run', 'deploy', 'stanke-dev',
      '--image=gcr.io/stanke-dev/stanke-dev:commit$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--tag=commit$SHORT_SHA',
      '--no-traffic',
      '--quiet'
    ]

  # add preview URL as a status check
  - name: 'gcr.io/${PROJECT_ID}/pr-status-poster'
    args: [
      '--project-id', '${PROJECT_ID}', 
      '--repo-name', 'davidstanke/${REPO_NAME}',
      '--commit-sha', '${COMMIT_SHA}',
      '--target-url', 'https://commit$SHORT_SHA---stanke-dev-t63odkzjiq-uc.a.run.app'
    ]